apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: test
spec:
  containers:
  - image: dihake/ingestion:v0.02
    name: test
    command: ["python", "-u", "workflows/main.py"]
    resources: {}
    envFrom:
    - secretRef:
        name: openai
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
