apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rag-api
  name: rag-api
  namespace: rag-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rag-api
  type: ClusterIP
status:
  loadBalancer: {}
